Forum/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Models
{
    public class Post
    {
        public int PostId { get; set; }

        [DisplayName("Post Title")]
        [Required(ErrorMessage = "This field is mandatory!")]
        public string Title { get; set; }

        [DisplayName("Post Content")]
        [Required(ErrorMessage = "This field is mandatory!")]
        public string Content { get; set; }

        public DateTime CreatedOn { get; set; }

        public ICollection<Comment> Comments { get; set; }
        public ApplicationUser User { get; set; }
    }
}

Forum/Controllers/ApplicationUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Forum.Data;
using Forum.Models;
using Forum.Repositories;
using Microsoft.AspNetCore.Authorization;

namespace Forum.Controllers
{
    public class ApplicationUserController : Controller
    {
        IApplicationUserRepository repo;

        public ApplicationUserController(ApplicationDbContext context)
        {
            repo = new ApplicationUserRepository(context);
        }

        // GET: ApplicationUsers
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(repo.GetAllApplicationUsers());
        }

        // Details for other users
        // GET: ApplicationUsers/Details/5
        [Authorize(Roles = "Admin,User")]
        public IActionResult Details(string id)
        {
            var applicationUser = repo.GetApplicationUserById(id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // Details for the user that is authenticated
        [Authorize(Roles = "Admin,User")]
        public IActionResult LogInDetails()
        {
            string name = User.Identity.Name;
            var applicationUser = repo.GetApplicationUser(name);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // GET: ApplicationUsers/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // GET: ApplicationUsers/Edit/5
        [Authorize(Roles = "Admin,User")]
        public IActionResult Edit()
        {

            string name = User.Identity.Name;

            var applicationUser = repo.GetApplicationUser(name);
            if (applicationUser == null)
            {
                return NotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public IActionResult Edit([Bind("name,FirstName,LastName,Address,City,PhoneNumber,Email")] ApplicationUser applicationUser)
        {
            string name = User.Identity.Name;
            if (ModelState.IsValid)
            {
                applicationUser = repo.UpdateApplicationUser(applicationUser, name);
                return RedirectToAction(nameof(LogInDetails));
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = repo.GetApplicationUserById(id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }


        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirmed(string id)
        {
            repo.DeleteApplicationUser(id);
            return RedirectToAction(nameof(Index));
        }


    }
}

Forum/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Forum.Data;
using Forum.Models;
using Forum.Repositories;
using Microsoft.AspNetCore.Authorization;

namespace Forum.Controllers
{
    public class CommentsController : Controller
    {
        CommentRepository repo;
        private int tempPostId = 0;

        public CommentsController(ApplicationDbContext context)
        {
            repo = new CommentRepository(context);
        }

        // GET: Comments
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(repo.GetAllComments());
        }

        // GET: Comments/Details/5
        [Authorize(Roles = "Admin")]
        public IActionResult Details(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var comment = repo.GetComment(id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create
        [Authorize(Roles = "Admin,User")]
        public IActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public IActionResult Create([Bind("CommentId,Content")] Comment comment, int postId)
        {
            if (ModelState.IsValid)
            {
                string name = User.Identity.Name;
                comment = repo.CreateComment(comment, name, postId);
                return RedirectToAction("Details", "Posts", new { id = postId });
            }
            return View(comment);
        }

        // GET: Comments/Edit/5
        [Authorize(Roles = "Admin,User")]
        public IActionResult Edit(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var comment = repo.GetComment(id);
            if (comment == null)
            {
                return NotFound();
            }
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public IActionResult Edit(int id, [Bind("CommentId,Content,CreatedOn")] Comment comment)
        {
            if (id != comment.CommentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                comment = repo.UpdateComment(comment);
                return RedirectToAction(nameof(Index));
            }
            return View(comment);
        }

        // GET: Comments/Delete/5
        [Authorize(Roles = "Admin,User")]
        public IActionResult Delete(int id, int postId)
        {
            tempPostId = postId;
            if (id < 0)
            {
                return NotFound();
            }

            var comment = repo.GetComment(id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [Authorize(Roles = "Admin,User")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            repo.DeleteComment(id);
            //return RedirectToAction("Details", "Posts", new { id = tempPostId });
            return RedirectToAction("Index", "Posts");
        }
    }
}

Forum/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Forum.Data;
using Forum.Models;
using Forum.Repositories;
using Microsoft.AspNetCore.Authorization;


namespace Forum.Controllers
{
    public class PostsController : Controller
    {
        IPostRepository repo;
        private readonly ApplicationDbContext _context;

        public PostsController(ApplicationDbContext context)
        {
            repo = new PostRepository(context);
            _context = context;
        }

        // GET: Posts
        public IActionResult Index()
        {
            string name = User.Identity.Name;
            return View(repo.GetAllPosts());
        }


        // GET: Posts/Details/5
        public IActionResult Details(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            Post post = repo.GetPost(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        //[Authorize(Roles = "Admin,User")]
        public IActionResult Create()
        {

            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("PostId,Title,Content")] Post post)
        {
            if (ModelState.IsValid)
            {
                string name = User.Identity.Name;
                post = repo.CreatePost(post, name);
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Edit/5
        [Authorize(Roles = "Admin,User")]
        public IActionResult Edit(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var post = repo.GetPost(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public IActionResult Edit(int id, [Bind("PostId,Title,Content")] Post post)
        {
            if (id != post.PostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                post = repo.UpdatePost(post);
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        [Authorize(Roles = "Admin,User")]
        public IActionResult Delete(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var post = repo.GetPost(id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public IActionResult DeleteConfirmed(int id)
        {
            repo.DeletePost(id);
            return RedirectToAction(nameof(Index));
        }

        // GET: Posts
        public IActionResult Search(string searchString)
        {
            var strings = searchString.Split(' ');
            var finalPosts = new List<Post>();
            List<Post> posts = _context.Posts
                .Include(m => m.Comments).ThenInclude(m => m.User)
                .ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                foreach (var post in posts)
                {
                    bool match_title = true;
                    bool match_content = true;
                    foreach (var splitString in strings)
                    {
                        if (!post.Title.Contains(splitString, System.StringComparison.CurrentCultureIgnoreCase))
                            match_title = false;
                        if (!post.Content.Contains(splitString, System.StringComparison.CurrentCultureIgnoreCase))
                            match_content = false;
                    }
                    if (match_title == true || match_content == true)
                        finalPosts.Add(post);
                }
            }
            return View("Index", finalPosts);
        }

    }
}

Forum/Views/Posts/Create.cshtml
@model Forum.Models.Post

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control"/>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Forum/Views/Posts/Delete.cshtml
@model Forum.Models.Post

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PostId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Forum/Views/Posts/Details.cshtml
@model Forum.Models.Post
@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Details";
}
<br />
<div>
    <a asp-action="Index">Back to List</a>
</div>

<div class="well">
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">@Html.DisplayFor(model => model.Title)</h4>
            <a asp-controller="ApplicationUser" asp-action="Details" asp-route-id="@Model.User.Id"><p class="text-right">@Html.DisplayFor(model => model.User.name)</p></a>
            <p>@Html.DisplayFor(model => model.Content) </p>
            <ul class="list-inline list-unstyled">
                <li><span><i class="glyphicon glyphicon-calendar"></i> @Html.DisplayFor(model => model.CreatedOn) </span></li>
            </ul>
        </div>
    </div>
</div>
@if (User.IsInRole("Admin") || @UserManager.GetUserName(User) == Model.User.UserName)
{
    <div>
        <a asp-action="Edit" asp-route-id="@Model.PostId" class="btn btn-warning">Edit</a>
        <a asp-action="Delete" asp-route-id="@Model.PostId" class=" btn btn-danger">Delete</a>
    </div>
}


@if (User.Identity.IsAuthenticated)
{
    <p>
        <br />
        Write a comment:
    </p>

    <form asp-action="Create" asp-controller="Comments" asp-route-postId="@Model.PostId">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <input type="text" value="" asp-for="Content" class="form-control" />
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Write comment" class="btn btn-primary" />
        </div>

    </form>
}

<div>
    <i class="glyphicon glyphicon-comment"></i>
    Comments (@Model.Comments.Count<Comment>)
</div>

@foreach (var item in Model.Comments.Reverse())
{
<div class="row">
    <div class="col-sm-1">
        <div class="thumbnail">
            <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
        </div><!-- /thumbnail -->
    </div><!-- /col-sm-1 -->
    <div class="col-sm-5">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>@Html.DisplayFor(modelItem => item.User.name)</strong> <span class="text-muted">@Html.DisplayFor(modelItem => item.CreatedOn)</span>
            </div>
            <div class="panel-body">
                @Html.DisplayFor(modelItem => item.Content)
            </div><!-- /panel-body -->
            @if (User.IsInRole("Admin") || @UserManager.GetUserName(User) == Model.User.UserName || @UserManager.GetUserName(User) == item.User.UserName)
            {
            <div>
                <a asp-controller="Comments" asp-action="Delete" asp-route-id="@item.CommentId" asp-route-postId="@Model.PostId"class=" btn btn-danger">Delete</a>
            </div>
            }
        </div><!-- /panel panel-default -->
    </div><!-- /col-sm-5 -->

</div><!-- /panel panel-default -->
}

Forum/Views/Posts/Edit.cshtml
@model Forum.Models.Post

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PostId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Forum/Views/Posts/Index.cshtml
@model IEnumerable<Forum.Models.Post>

@{
    ViewData["Title"] = "Index";
}


<table class="table">
   <tr>
       <td>
           <h1>Posts</h1>
       </td>
       <td>
           <h2>
           <div align="right">
               <form asp-controller="Posts" asp-action="Search" method="get" accept-charset="utf-8">
                   <input type="text" name="SearchString" placeholder="Search">
               </form>
           </div>
           </h2>

       </td>
   </tr>
</table>


@if (User.Identity.IsAuthenticated)
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}




    @foreach (var item in Model.Reverse())
    {
        <div class="well">
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading"><a asp-action="Details" asp-route-id="@item.PostId">@Html.DisplayFor(modelItem => item.Title) </a></h4>
                    <a asp-controller="ApplicationUser" asp-action="Details" asp-route-id="@item.User.Id"><p class="text-right">@Html.DisplayFor(modelItem => item.User.name)</p></a>
                    <p>@Html.DisplayFor(modelItem => item.Content) </p>
                    <ul class="list-inline list-unstyled">
                        <li><span><i class="glyphicon glyphicon-calendar"></i> @Html.DisplayFor(modelItem => item.CreatedOn) </span></li>
                        <li>|</li>

                        <span>
                            <i class="glyphicon glyphicon-comment"></i>
                            <a asp-action="Details" asp-route-id="@item.PostId" class="btn btn-light">@item.Comments.Count<Comment></a>
                        </span>

                        <li>|</li>
                        <li>
                            <a asp-action="Details" asp-route-id="@item.PostId" class="btn btn-light">Details</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    }